remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme #
title: calin.dev
description: Something something dark side.

author: calin
url:         "https://beta.calin.dev"
extensions: ['smart', 'tables', 'with_toc_data']
permalink: /blog/:year/:month/:day/:title/
